# Site settings
title: Templar Crypto Systems
email: dmcgillivray@templarctypro.com
url: http://templarcrypto.com
description: "Templar Crypto Systems: Flight Controller for Elite:Dangerous and Star Citizen."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Templar Crypto Systems

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/thispunklife
  - title: facebook
    url: https://www.facebook.com/templarcrypto
  - title: github
    url: https://github.com/templargalactic/flightcontroller
  - title: imgur
    url: http://phebos.imgur.com/all/



# Build settings
markdown: kramdown
permalink: pretty
